version: "3.4"

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: nginx.Dockerfile
    image: ise_nginx:latest
    container_name: proxy_registry
    depends_on:
      - registry
      - registry-ui
    ports:
      - "5000:5000"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    restart: always

