version: "3.4"

services:

  registry:
    container_name: registry
    image: registry:latest
    expose:
     - "5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /home/bockstaller/container_data:/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"


  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui
    expose:
      - "80"
    restart: always
    environment:
      REGISTRY_URL:
